name: lint and test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
        # Action gives to setup the PHP environment to test application
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          # Specify the PHP version
          php-version: '8.1'

      - name: setup all dependencies
        run: composer install
      - uses: actions/checkout@v2
      - run: make install
      - run: make lint
      - run: make test
